#!/bin/sh
#
#  Install
###########################################################################
#
#  Purpose:  This script invokes the Ant utility to perform the build for
#            this product.
#
#  Usage:  Install
#
###########################################################################

cd `dirname $0`

. ./gxdindexer.config

if [ ! -d ${FILE_DIR} ]
then
    mkdir -p ${FILE_DIR}
fi

if [ ! -d ${LOG_DIR} ]
then
    mkdir -p ${LOG_DIR}
fi

cd bin
if [ -h buildAllIndexes ]; then
    rm buildAllIndexes
fi
ln -s ${BUILD_SCRIPT} buildAllIndexes
cd ..

if [ ! -e "${MAVEN_REPO_LOCAL}" ] ; then
  echo "MAVEN_REPO_LOCAL is not defined or does not exist."
  exit 1
fi
mvn -Dmaven.repo.local=${MAVEN_REPO_LOCAL} clean package
